
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const About = lazy(() => import("./pages/About.tsx"));
const Api = lazy(() => import("./pages/Api.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Docs = lazy(() => import("./pages/Docs.tsx"));
const NotFound = lazy(() => import("./pages/NotFound.tsx"));
const Status = lazy(() => import("./pages/Status.tsx"));
const Tickets = lazy(() => import("./pages/Tickets.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/about", element: <About />},
	{ path: "/api", element: <Api />},
	{ path: "/", element: <App />},
	{ path: "/dashboard", element: <Dashboard />},
	{ path: "/docs", element: <Docs />},
	{ path: "/not-found", element: <NotFound />},
	{ path: "/notfound", element: <NotFound />},
	{ path: "/status", element: <Status />},
	{ path: "/tickets", element: <Tickets />},

];
